### ISSUE TITLE
Got non zero exit code

### ISSUE THREAD

**Issue by micdic** [mfpierre/coreml-scikit-example#1]
Hi there, 
running this sample on a Mac OS 10.13.1 and Python 2.7.14 :: Anaconda i got this runtime error.
on this method  

**coreml_model = coremltools.converters.sklearn.convert(model, iris.feature_names, 'iris class')**

### Here the traceback:
----------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    coreml_model = coremltools.converters.sklearn.convert(model, iris.feature_names, 'iris class')
  File "/Users/micheledicapua/anaconda2/lib/python2.7/site-packages/coremltools/converters/sklearn/_converter.py", line 146, in convert
    sk_obj, input_features, output_feature_names, class_labels = None)
  File "/Users/micheledicapua/anaconda2/lib/python2.7/site-packages/coremltools/converters/sklearn/_converter_internal.py", line 297, in _convert_sklearn_model
    last_spec = last_sk_m.convert(last_sk_obj, current_input_features, output_features)._spec
  File "/Users/micheledicapua/anaconda2/lib/python2.7/site-packages/coremltools/converters/sklearn/_logistic_regression.py", line 45, in convert
    return _MLModel(_convert(model, feature_names, target))
  File "/Users/micheledicapua/anaconda2/lib/python2.7/site-packages/coremltools/models/model.py", line 131, in __init__
    self.__proxy__ = _get_proxy_from_spec(filename)
  File "/Users/micheledicapua/anaconda2/lib/python2.7/site-packages/coremltools/models/model.py", line 55, in _get_proxy_from_spec
    return _MLModelProxy.fromSpec(filename)
RuntimeError: Got non-zero exit code 1 from coremlcompiler: coremlcompiler: Error: Error reading protobuf spec. validator error: Description of multiarray feature '__feature_vector__' has an invalid or unspecified dataType. It must be specified as DOUBLE, FLOAT32 or INT32

**Comment by micdic** [comment]
It' seems to work only after a simple reboot of Anaconda VM.
